# Generated by Django 4.2 on 2026-05-31 02:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(max_length=5)),
                ('chapter_major', models.CharField(max_length=50)),
                ('chapter_middle', models.CharField(max_length=50)),
                ('chapter_minor', models.CharField(max_length=50)),
                ('problem_subtype', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('question_with_options', models.TextField(blank=True, null=True)),
                ('question_image_bbox', models.JSONField(default=list)),
                ('answer', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_major', models.CharField(max_length=50)),
                ('chapter_middle', models.CharField(max_length=50)),
                ('chapter_minor', models.CharField(blank=True, max_length=50, null=True)),
                ('problem_count', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_session',
            },
        ),
        migrations.CreateModel(
            name='WeaknessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('all_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weakness_report', to='quiz.quizsession')),
            ],
            options={
                'db_table': 'weakness_report',
            },
        ),
        migrations.CreateModel(
            name='WeakSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_subtype', models.CharField(max_length=100)),
                ('wrong_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_subtypes', to='quiz.weaknessreport')),
            ],
            options={
                'db_table': 'weak_subtype',
                'ordering': ['rank'],
                'unique_together': {('report', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('order_index', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.problem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='quiz.weaknessreport')),
                ('weak_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='quiz.weaksubtype')),
            ],
            options={
                'db_table': 'recommendation',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.problem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.quizsession')),
            ],
            options={
                'db_table': 'session_result',
                'unique_together': {('session', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='SessionProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.problem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_problems', to='quiz.quizsession')),
            ],
            options={
                'db_table': 'session_problem',
                'unique_together': {('session', 'order_index')},
            },
        ),
    ]
