# Generated by Django 4.2 on 2026-06-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_quizable',
            field=models.BooleanField(default=False),
        ),
    ]
