# Generated by Django 4.2 on 2026-06-09 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_problem_is_quizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sessions', to='quiz.quizsession'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='session_type',
            field=models.CharField(choices=[('normal', '일반 세션'), ('review_1', '1차 오답 보완'), ('review_2', '2차 오답 보완')], default='normal', max_length=20),
        ),
    ]
