# Generated by Django 4.2 on 2026-06-14 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizsession_parent_session_quizsession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default='중2', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubtypeMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_subtype', models.CharField(max_length=100)),
                ('mastered', models.BooleanField(default=False)),
                ('accuracy_before', models.FloatField(blank=True, null=True)),
                ('accuracy_after', models.FloatField(blank=True, null=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtype_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subtype_mastery',
                'unique_together': {('user', 'problem_subtype')},
            },
        ),
    ]
