# Generated by Django 4.2 on 2026-06-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_user_grade_user_last_active_date_user_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='backfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='extraction_status',
            field=models.CharField(blank=True, help_text='recovered / recovered_needs_review / missing_raw_json / no_option_items_in_raw / original(처음부터 정상이었음)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='option_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('mixed_with_image', 'mixed_with_image')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='recovered_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProblemAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_role', models.CharField(help_text='원본 class_name 그대로 저장: 정답(이미지) / 오답(이미지) 등', max_length=30)),
                ('image_path', models.CharField(max_length=500)),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='quiz.problem')),
            ],
        ),
        migrations.AddIndex(
            model_name='problemasset',
            index=models.Index(fields=['problem'], name='quiz_proble_problem_88cff6_idx'),
        ),
    ]
