# Generated by Django 4.2 on 2026-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_problem_answer_match_problem_backfilled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='grading_answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
