# Generated by Django 4.2 on 2026-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_problem_grading_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_multi_answer',
            field=models.BooleanField(default=False),
        ),
    ]
