# Generated by Django 4.2 on 2026-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_problem_is_multi_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_chapter_major',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='current_chapter_middle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='session_type',
            field=models.CharField(choices=[('normal', '일반 세션'), ('diagnosis', '빠른 진단'), ('review_1', '1차 오답 보완'), ('review_2', '2차 오답 보완')], default='normal', max_length=20),
        ),
    ]
