# Generated by Django 4.2 on 2026-06-25 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_user_current_chapter_major_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='ai_feedback',
        ),
        migrations.AlterField(
            model_name='problem',
            name='extraction_status',
            field=models.CharField(blank=True, help_text='recovered / recovered_needs_review', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='weak_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_problems', to='quiz.weaksubtype'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_quizable'], name='problem_is_quiz_4d94be_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['problem_subtype'], name='problem_problem_bc15be_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_quizable', 'difficulty'], name='problem_is_quiz_a37147_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_quizable', 'chapter_middle'], name='problem_is_quiz_66db31_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quiz.problem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
